'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AppShell } from '../../components/AppShell';
import { Card, ErrorText, Field, PrimaryButton, Select, TextInput } from '../../components/ui';
import { api, ApiError } from '../../lib/api';
import type { Invoice } from '../../lib/types';

export default function PaymentsPage(){const [invoices,setInvoices]=useState<Invoice[]>([]);const [selected,setSelected]=useState('');const [amount,setAmount]=useState('');const [method,setMethod]=useState('cash');const [reference,setReference]=useState('');const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);const [saving,setSaving]=useState(false);const load=()=>api.get<Invoice[]>('/fees/invoices').then(setInvoices).catch(e=>setError(e instanceof ApiError?e.message:'Failed to load invoices.'));useEffect(()=>{load()},[]);const invoice=invoices.find(i=>i.id===selected);async function submit(e:FormEvent){e.preventDefault();if(!selected)return;setSaving(true);setError(null);setSuccess(null);try{await api.post(`/fees/invoices/${selected}/payments`,{amount:Number(amount),method,reference:reference||undefined});setAmount('');setReference('');setSuccess('Payment recorded.');await load();}catch(e){setError(e instanceof ApiError?e.message:'Failed to record payment.')}finally{setSaving(false)}}return <AppShell><div className="mb-8"><div className="font-mono text-xs uppercase tracking-widest text-margin mb-2">Finance</div><h1 className="font-display text-4xl uppercase text-ink">Payments</h1><p className="mt-2 text-sm text-ink-soft">Record payments against school invoices. Overpayments are rejected by the API.</p></div><Card className="max-w-2xl"><form onSubmit={submit} className="space-y-4"><Field label="Invoice"><Select required value={selected} onChange={e=>{setSelected(e.target.value);const i=invoices.find(x=>x.id===e.target.value);setAmount(i?String(Number(i.amountDue)-Number(i.amountPaid)):'')}}><option value="">Select invoice</option>{invoices.filter(i=>i.status!=='PAID').map(i=><option key={i.id} value={i.id}>{i.student.firstName} {i.student.lastName} · {i.feeStructure.name} · balance {formatCurrency(Number(i.amountDue)-Number(i.amountPaid))}</option>)}</Select></Field>{invoice&&<div className="text-sm text-ink-soft border border-paper-line bg-paper p-3">Current balance: <strong>{formatCurrency(Number(invoice.amountDue)-Number(invoice.amountPaid))}</strong></div>}<div className="grid grid-cols-2 gap-4"><Field label="Amount"><TextInput required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Method"><Select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="online">Online</option><option value="cheque">Cheque</option><option value="bank_transfer">Bank transfer</option></Select></Field></div><Field label="Reference (optional)"><TextInput value={reference} onChange={e=>setReference(e.target.value)} placeholder="Receipt / transaction reference"/></Field><ErrorText>{error}</ErrorText>{success&&<p className="text-sm text-green-700">{success}</p>}<PrimaryButton type="submit" disabled={saving||!selected}>{saving?'Recording…':'Record payment'}</PrimaryButton></form></Card></AppShell>}
function formatCurrency(n:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
