'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AppShell } from '../../components/AppShell';
import { Card, ErrorText, Field, GhostButton, PrimaryButton, Select, TextInput } from '../../components/ui';
import { api, ApiError } from '../../lib/api';
import type { FeeStructure, Invoice, Student } from '../../lib/types';

export default function InvoicesPage() {
  const [invoices,setInvoices]=useState<Invoice[]|null>(null); const [students,setStudents]=useState<Student[]>([]); const [structures,setStructures]=useState<FeeStructure[]>([]); const [show,setShow]=useState(false); const [error,setError]=useState<string|null>(null); const [formError,setFormError]=useState<string|null>(null); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({studentId:'',feeStructureId:'',amountDue:'',dueDate:''});
  const load=()=>api.get<Invoice[]>('/fees/invoices').then(setInvoices).catch(e=>setError(e instanceof ApiError?e.message:'Failed to load invoices.'));
  useEffect(()=>{load(); api.get<Student[]>('/students').then(setStudents).catch(()=>{}); api.get<FeeStructure[]>('/fees/structures').then(setStructures).catch(()=>{});},[]);
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setFormError(null);try{await api.post('/fees/invoices',{...form,amountDue:Number(form.amountDue)});setShow(false);setForm({studentId:'',feeStructureId:'',amountDue:'',dueDate:''});load();}catch(e){setFormError(e instanceof ApiError?e.message:'Failed to create invoice.')}finally{setSaving(false)}}
  return <AppShell><div className="flex items-start justify-between mb-8"><div><div className="font-mono text-xs uppercase tracking-widest text-margin mb-2">Finance</div><h1 className="font-display text-4xl uppercase text-ink">Invoices</h1></div><PrimaryButton onClick={()=>setShow(!show)}>{show?'Cancel':'+ New invoice'}</PrimaryButton></div>
  {show&&<Card className="mb-8"><form onSubmit={submit} className="grid grid-cols-2 gap-4"><Field label="Student"><Select required value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName}{s.rollNumber?` · ${s.rollNumber}`:''}</option>)}</Select></Field><Field label="Fee structure"><Select required value={form.feeStructureId} onChange={e=>{const v=e.target.value;const f=structures.find(x=>x.id===v);setForm({...form,feeStructureId:v,amountDue:f?String(f.amount):form.amountDue})}}><option value="">Select structure</option>{structures.map(f=><option key={f.id} value={f.id}>{f.name} · {formatCurrency(Number(f.amount))}</option>)}</Select></Field><Field label="Amount due"><TextInput required type="number" min="1" step="0.01" value={form.amountDue} onChange={e=>setForm({...form,amountDue:e.target.value})}/></Field><Field label="Due date"><TextInput required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field><div className="col-span-2"><ErrorText>{formError}</ErrorText><PrimaryButton type="submit" disabled={saving}>{saving?'Creating…':'Create invoice'}</PrimaryButton><GhostButton type="button" className="ml-2" onClick={()=>setShow(false)}>Cancel</GhostButton></div></form></Card>}
  <ErrorText>{error}</ErrorText>{invoices&&<div className="bg-[#FFFDF8] border border-paper-line rounded-sm overflow-hidden"><table className="w-full text-sm"><thead><tr className="bg-board text-chalk text-left font-mono text-xs uppercase"><th className="px-4 py-3">Student</th><th className="px-4 py-3">Fee</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Balance</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{invoices.map((i,n)=><tr key={i.id} className={n%2===0?'bg-white':'bg-paper/60'}><td className="px-4 py-4 font-medium">{i.student.firstName} {i.student.lastName}</td><td className="px-4 py-4 text-ink-soft">{i.feeStructure.name}</td><td className="px-4 py-4 font-mono">{i.dueDate.slice(0,10)}</td><td className="px-4 py-4 font-mono">{formatCurrency(Number(i.amountDue)-Number(i.amountPaid))}</td><td className="px-4 py-4"><span className="font-mono text-xs">{i.status}</span></td></tr>)}</tbody></table></div>}</AppShell>
}
function formatCurrency(n:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
