'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AppShell } from '../../components/AppShell';
import { Card, ErrorText, Field, GhostButton, PrimaryButton, Select, TextInput } from '../../components/ui';
import { api, ApiError } from '../../lib/api';
import type { FeeStructure } from '../../lib/types';

export default function FeeStructuresPage(){const [items,setItems]=useState<FeeStructure[]|null>(null);const [show,setShow]=useState(false);const [error,setError]=useState<string|null>(null);const [formError,setFormError]=useState<string|null>(null);const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'',amount:'',frequency:'monthly'});const load=()=>api.get<FeeStructure[]>('/fees/structures').then(setItems).catch(e=>setError(e instanceof ApiError?e.message:'Failed to load fee structures.'));useEffect(()=>{load()},[]);async function submit(e:FormEvent){e.preventDefault();setSaving(true);setFormError(null);try{await api.post('/fees/structures',{...form,amount:Number(form.amount)});setForm({name:'',amount:'',frequency:'monthly'});setShow(false);load()}catch(e){setFormError(e instanceof ApiError?e.message:'Failed to create fee structure.')}finally{setSaving(false)}}return <AppShell><div className="flex items-start justify-between mb-8"><div><div className="font-mono text-xs uppercase tracking-widest text-margin mb-2">Finance</div><h1 className="font-display text-4xl uppercase text-ink">Fee structures</h1><p className="mt-2 text-sm text-ink-soft">Define the charges that invoices can use.</p></div><PrimaryButton onClick={()=>setShow(!show)}>{show?'Cancel':'+ New fee structure'}</PrimaryButton></div>{show&&<Card className="mb-8"><form onSubmit={submit} className="grid grid-cols-3 gap-4"><Field label="Name"><TextInput required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Tuition — Class 8"/></Field><Field label="Amount"><TextInput required type="number" min="1" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Frequency"><Select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option><option value="one-time">One-time</option></Select></Field><div className="col-span-3"><ErrorText>{formError}</ErrorText><PrimaryButton type="submit" disabled={saving}>{saving?'Creating…':'Create fee structure'}</PrimaryButton><GhostButton type="button" className="ml-2" onClick={()=>setShow(false)}>Cancel</GhostButton></div></form></Card>}{error&&<ErrorText>{error}</ErrorText>}{items&&<div className="bg-[#FFFDF8] border border-paper-line rounded-sm overflow-hidden"><table className="w-full text-sm"><thead><tr className="bg-board text-chalk text-left font-mono text-xs uppercase"><th className="px-4 py-3">Name</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Frequency</th></tr></thead><tbody>{items.map((f,i)=><tr key={f.id} className={i%2===0?'bg-white':'bg-paper/60'}><td className="px-4 py-4 font-medium">{f.name}</td><td className="px-4 py-4 font-mono">{formatCurrency(Number(f.amount))}</td><td className="px-4 py-4 text-ink-soft">{f.frequency}</td></tr>)}</tbody></table></div>}</AppShell>}
function formatCurrency(n:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
